### PR TITLE
added support for TMS layer, used by Geoserver layers

### PR DESCRIPTION
**Pull request by stefanocudini**
this patch allow loading of TMS geoserver layers

Vector Tile server byg Geoserver using this plugin:
http://suite.opengeo.org/docs/latest/dataadmin/vectortiles/index.html

### CODE REVIEW

**Comment by stefanocudini** [comment]
@rgwozdz this is important for geoserver compatibility

**Review by danielduhh — CHANGES_REQUESTED** [review]
thanks for the PR @stefanocudini. I wasn't able to load your example tms layer. Could you create a new example html and js file in /examples (keep basic.js as is) with a public tms layer; as well as add this option to the docs/configuration.md file

**Comment by stefanocudini** [comment]
Sorry @danielduhh for now I don't have a public TMS layer for making an example.
But this PR is tested well for implement **tms: true** option support

**Comment by stefanocudini** [comment]
@danielduhh I'm just fix any bugs about forked version, now it work please, merge this.
Just now and support was added with tms _option: true_

**Pull request closed without merging**
