### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by henryptung**
Some zoomend listeners attached to global map
were not being properly cleaned up when the vector layer
is removed. If the layer is being added and removed
multiple times (or even if the user zooms repeatedly),
the layer features will leak and at high scale,
the browser OOMs. Added some more eventing propagation
on layer removal to handle this case.

### CODE REVIEW

**Comment by rgwozdz** [comment]
After merging this pull request, it became evident that several of the applications in the examples directory were no longer functional.  Thus I reverted the merge of this PR.  Do you have an idea as to why this PR might break the examples?

**Comment by henryptung** [comment]
@rgwozdz Do you know which examples were failing?

There are some that seem to fail (like dynamic-label), but because they reference resources which aren't in the repo, instead pulled in by NPM (like vector-tile).

Let me try to find one that works with the previous commit but fails with the leaks-fix, and get back to you.

**Comment by henryptung** [comment]
So this is my readout of the current examples:

* basic: Seems to work fine.
* confetti: Seems to work fine.
* dynamic-label: Pulls from a local tile source at http://localhost:3001/services/vector-tiles/GADM/{z}/{x}/{y}.pbf? Not sure this will work without auxiliary data.
* gadm: Same as dynamic-label, pulls from http://localhost:3000/services/vector-tiles/gadm/{z}/{x}/{y}.pbf.
* india-aggregations: Seems to behave identically on 7fa865e vs. my branch, lots of 0's and AJAX errors though; something seems unhealthy about this example, probably need to look at the backend calls being made.
* india-label: Bunch of "Administrative unit not available", but otherwise working fine.
* mapbox-source: Something seriously funky and broken about selection; feature IDs are clearly out of whack, selecting things will randomly select across multiple tiles, features split at tile boundaries don't have consistent IDs and aren't selected together, selecting labels throws errors and selects no features. Still identical behavior before/after PR.
* osm_seattle: What? Why is this a copy of confetti, and it even references confetti.js? Same behavior.
* static-label: Seems fine, same behavior before-and-after as far as I can tell.
* visibleLayers: Not sure what is/is not supposed to be happening here, but one layer of polygons shows up and works fine. Same behavior before-and-after.

Please feel free to go through and verify, but not sure what to do about the missing tile sources for GADM; `localhost` certainly isn't a viable source for that data.

**Comment by rgwozdz** [comment]
Thank you for your reply.  Can you re-submit the pull request?

On Dec 19, 2015, at 3:53 PM, henryptung <notifications@github.com<mailto:notifications@github.com>> wrote:


So this is my readout of the current examples:

  *   basic: Seems to work fine.
  *   confetti: Seems to work fine.
  *   dynamic-label: Pulls from a local tile source at http://localhost:3001/services/vector-tiles/GADM/{z}/{x}/{y}.pbf? Not sure this will work without auxiliary data.
  *   gadm: Same as dynamic-label, pulls from http://localhost:3000/services/vector-tiles/gadm/{z}/{x}/{y}.pbf.
  *   india-aggregations: Seems to behave identically on 7fa865e<https://github.com/SpatialServer/Leaflet.MapboxVectorTile/commit/7fa865e7538d69e35b11ece875add39faf410c27> vs. my branch, lots of 0's and AJAX errors though; something seems unhealthy about this example, probably need to look at the backend calls being made.
  *   india-label: Bunch of "Administrative unit not available", but otherwise working fine.
  *   mapbox-source: Something seriously funky and broken about selection; feature IDs are clearly out of whack, selecting things will randomly select across multiple tiles, features split at tile boundaries don't have consistent IDs and aren't selected together, selecting labels throws errors and selects no features. Still identical behavior before/after PR.
  *   osm_seattle: What? Why is this a copy of confetti, and it even references confetti.js? Same behavior.
  *   static-label: Seems fine, same behavior before-and-after as far as I can tell.
  *   visibleLayers: Not sure what is/is not supposed to be happening here, but one layer of polygons shows up and works fine. Same behavior before-and-after.

Please feel free to go through and verify, but not sure what to do about the missing tile sources for GADM; localhost certainly isn't a viable source for that data.

**Pull request merged**
