### PR TITLE
Add multiple draw passes for hover

### PR DESCRIPTION
**Pull request by henryptung**
Modify visibleLayers to allow for mapping.

* visibleLayers can now be specified as a { [string]: string } map.
      This allows specification of multiple, differently-styled render
      passes based on the same layer data.  Is particularly useful for
      rendering overlay-style interactive elements (like hover).
* Empty visibleLayers array now means no layers, instead of all layers
      shown.  Slightly API-breaking, though this seems like the more
      consistent value (probably better to treat absent/null as
      the special "show all" value, rather than empty array, which
      logically seems more like "show none".
* Also exposed `MVTFeature.redraw` method, to allow individual features
     to be restyled rapidly during hover interaction without redrawing
     the whole layer (or using a double `.toggle()` hack).

### CODE REVIEW

**Comment by henryptung** [comment]
In thinking a little more about this, I think I want to refactor the redrawTiles() method out of MVTFeature, and have it instead report the tiles it touches to MVTLayer, which can collect/union those tiles across a list of features for rerendering.  This means that updating the style of e.g. 10 features won't risk spuriously rerendering a tile 9 more times than necessary.

**Comment by henryptung** [comment]
Ping! Just wanted to check on this; if you don't have time to take a look, just let me know and I can keep a fork up, but just want to know what I should point my project at.  Thanks!

**Comment by apollolm** [comment]
Thanks Henry - I don't have bandwidth right now to look at this, so please keep your fork up for the time being...

**Comment by apollolm** [comment]
Hi Henry - all of this work you’ve done is great!

I’m going to be leaving my current company, and probably won’t be working on this much in the future.

I’ve created a new team in the repo, and given it admin rights.  I’ve sent a request for you to become part of that team so that you can be an admin on this repo (if you’re interested).
Then you can merge all of your changes into master and carry it forward!

I’ll still be poking around with it here and there, but I’ll be out of commission for awhile during the transition to the new role.

Good luck and thanks!

Ryan

**Pull request closed without merging**
